In [2]:
import pandas as pd

dataset=pd.read_csv('telecom-2009_2023.csv').values
open_value=dataset[:,2]
print(open_value[:5])

open_value=open_value.reshape(-1,1) #convering into a column vector
print(open_value[:5])

print(open_value.shape)

[48.0 47.0 46.0 45.5 45.5]
[[48.0]
 [47.0]
 [46.0]
 [45.5]
 [45.5]]
(3239, 1)


In [3]:
from matplotlib import pyplot as plt

plt.plot(open_value)
plt.xlabel('Date')
plt.ylabel('Open Value/$')
plt.show()

In [4]:
from sklearn.preprocessing import MinMaxScaler


scaler=MinMaxScaler(feature_range=(0,1))
scaled_open_value=scaler.fit_transform(open_value)

print(open_value[:5])
print(scaled_open_value[:5])

[[48.0]
 [47.0]
 [46.0]
 [45.5]
 [45.5]]
[[0.30208333]
 [0.29166667]
 [0.28125   ]
 [0.27604167]
 [0.27604167]]


In [5]:
data=[]
target=[]

for i in range(50,open_value.shape[0]):
    data.append(scaled_open_value[i-50:i])
    target.append(scaled_open_value[i])

In [6]:
import numpy as np

data_np=np.array(data)
target_np=np.array(target)

print(data_np.shape)
print(target_np.shape)

(3189, 50, 1)
(3189, 1)


In [7]:
np.save('data',data)
np.save('target',target)

In [8]:
import joblib
joblib.dump(scaler, 'stock-scaler.sav')


['stock-scaler.sav']

['scaler.joblib']